INSERT INTO Pays (libelle_pays) VALUES ('Afghanistan');
INSERT INTO Pays (libelle_pays) VALUES ('Albania');
INSERT INTO Pays (libelle_pays) VALUES ('Algeria');
INSERT INTO Pays (libelle_pays) VALUES ('American Samoa');
INSERT INTO Pays (libelle_pays) VALUES ('Andorra');
INSERT INTO Pays (libelle_pays) VALUES ('Angola');
INSERT INTO Pays (libelle_pays) VALUES ('Anguilla');
INSERT INTO Pays (libelle_pays) VALUES ('Antarctica');
INSERT INTO Pays (libelle_pays) VALUES ('Antigua and Barbuda');
INSERT INTO Pays (libelle_pays) VALUES ('Argentina');
INSERT INTO Pays (libelle_pays) VALUES ('Armenia');
INSERT INTO Pays (libelle_pays) VALUES ('Aruba');
INSERT INTO Pays (libelle_pays) VALUES ('Australia');
INSERT INTO Pays (libelle_pays) VALUES ('Austria');
INSERT INTO Pays (libelle_pays) VALUES ('Azerbaijan');
INSERT INTO Pays (libelle_pays) VALUES ('Bahamas');
INSERT INTO Pays (libelle_pays) VALUES ('Bahrain');
INSERT INTO Pays (libelle_pays) VALUES ('Bangladesh');
INSERT INTO Pays (libelle_pays) VALUES ('Barbados');
INSERT INTO Pays (libelle_pays) VALUES ('Belarus');
INSERT INTO Pays (libelle_pays) VALUES ('Belgium');
INSERT INTO Pays (libelle_pays) VALUES ('Belize');
INSERT INTO Pays (libelle_pays) VALUES ('Benin');
INSERT INTO Pays (libelle_pays) VALUES ('Bermuda');
INSERT INTO Pays (libelle_pays) VALUES ('Bhutan');
INSERT INTO Pays (libelle_pays) VALUES ('Bosnia and Herzegovina');
INSERT INTO Pays (libelle_pays) VALUES ('Botswana');
INSERT INTO Pays (libelle_pays) VALUES ('Bouvet Island');
INSERT INTO Pays (libelle_pays) VALUES ('Brazil');
INSERT INTO Pays (libelle_pays) VALUES ('British Indian Ocean Territory');
INSERT INTO Pays (libelle_pays) VALUES ('Brunei Darussalam');
INSERT INTO Pays (libelle_pays) VALUES ('Bulgaria');
INSERT INTO Pays (libelle_pays) VALUES ('Burkina Faso');
INSERT INTO Pays (libelle_pays) VALUES ('Burundi');
INSERT INTO Pays (libelle_pays) VALUES ('Cambodia');
INSERT INTO Pays (libelle_pays) VALUES ('Cameroon');
INSERT INTO Pays (libelle_pays) VALUES ('Canada');
INSERT INTO Pays (libelle_pays) VALUES ('Cape Verde');
INSERT INTO Pays (libelle_pays) VALUES ('Cayman Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Central African Republic');
INSERT INTO Pays (libelle_pays) VALUES ('Chad');
INSERT INTO Pays (libelle_pays) VALUES ('Chile');
INSERT INTO Pays (libelle_pays) VALUES ('China');
INSERT INTO Pays (libelle_pays) VALUES ('Christmas Island');
INSERT INTO Pays (libelle_pays) VALUES ('Cocos (Keeling) Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Colombia');
INSERT INTO Pays (libelle_pays) VALUES ('Comoros');
INSERT INTO Pays (libelle_pays) VALUES ('Congo');
INSERT INTO Pays (libelle_pays) VALUES ('Cook Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Costa Rica');
INSERT INTO Pays (libelle_pays) VALUES ('Croatia');
INSERT INTO Pays (libelle_pays) VALUES ('Cuba');
INSERT INTO Pays (libelle_pays) VALUES ('Cyprus');
INSERT INTO Pays (libelle_pays) VALUES ('Czech Republic');
INSERT INTO Pays (libelle_pays) VALUES ('Denmark');
INSERT INTO Pays (libelle_pays) VALUES ('Djibouti');
INSERT INTO Pays (libelle_pays) VALUES ('Dominica');
INSERT INTO Pays (libelle_pays) VALUES ('Dominican Republic');
INSERT INTO Pays (libelle_pays) VALUES ('Ecuador');
INSERT INTO Pays (libelle_pays) VALUES ('Egypt');
INSERT INTO Pays (libelle_pays) VALUES ('El Salvador');
INSERT INTO Pays (libelle_pays) VALUES ('Equatorial Guinea');
INSERT INTO Pays (libelle_pays) VALUES ('Eritrea');
INSERT INTO Pays (libelle_pays) VALUES ('Estonia');
INSERT INTO Pays (libelle_pays) VALUES ('Ethiopia');
INSERT INTO Pays (libelle_pays) VALUES ('Falkland Islands (Malvinas)');
INSERT INTO Pays (libelle_pays) VALUES ('Faroe Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Fiji');
INSERT INTO Pays (libelle_pays) VALUES ('Finland');
INSERT INTO Pays (libelle_pays) VALUES ('France');
INSERT INTO Pays (libelle_pays) VALUES ('French Guiana');
INSERT INTO Pays (libelle_pays) VALUES ('French Polynesia');
INSERT INTO Pays (libelle_pays) VALUES ('French Southern Territories');
INSERT INTO Pays (libelle_pays) VALUES ('Gabon');
INSERT INTO Pays (libelle_pays) VALUES ('Gambia');
INSERT INTO Pays (libelle_pays) VALUES ('Georgia');
INSERT INTO Pays (libelle_pays) VALUES ('Germany');
INSERT INTO Pays (libelle_pays) VALUES ('Ghana');
INSERT INTO Pays (libelle_pays) VALUES ('Gibraltar');
INSERT INTO Pays (libelle_pays) VALUES ('Greece');
INSERT INTO Pays (libelle_pays) VALUES ('Greenland');
INSERT INTO Pays (libelle_pays) VALUES ('Grenada');
INSERT INTO Pays (libelle_pays) VALUES ('Guadeloupe');
INSERT INTO Pays (libelle_pays) VALUES ('Guam');
INSERT INTO Pays (libelle_pays) VALUES ('Guatemala');
INSERT INTO Pays (libelle_pays) VALUES ('Guernsey');
INSERT INTO Pays (libelle_pays) VALUES ('Guinea');
INSERT INTO Pays (libelle_pays) VALUES ('Guinea-Bissau');
INSERT INTO Pays (libelle_pays) VALUES ('Guyana');
INSERT INTO Pays (libelle_pays) VALUES ('Haiti');
INSERT INTO Pays (libelle_pays) VALUES ('Heard Island and McDonald Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Holy See (Vatican City State)');
INSERT INTO Pays (libelle_pays) VALUES ('Honduras');
INSERT INTO Pays (libelle_pays) VALUES ('Hong Kong');
INSERT INTO Pays (libelle_pays) VALUES ('Hungary');
INSERT INTO Pays (libelle_pays) VALUES ('Iceland');
INSERT INTO Pays (libelle_pays) VALUES ('India');
INSERT INTO Pays (libelle_pays) VALUES ('Indonesia');
INSERT INTO Pays (libelle_pays) VALUES ('Iran');
INSERT INTO Pays (libelle_pays) VALUES ('Iraq');
INSERT INTO Pays (libelle_pays) VALUES ('Ireland');
INSERT INTO Pays (libelle_pays) VALUES ('Isle of Man');
INSERT INTO Pays (libelle_pays) VALUES ('Italy');
INSERT INTO Pays (libelle_pays) VALUES ('Jamaica');
INSERT INTO Pays (libelle_pays) VALUES ('Japan');
INSERT INTO Pays (libelle_pays) VALUES ('Jersey');
INSERT INTO Pays (libelle_pays) VALUES ('Jordan');
INSERT INTO Pays (libelle_pays) VALUES ('Kazakhstan');
INSERT INTO Pays (libelle_pays) VALUES ('Kenya');
INSERT INTO Pays (libelle_pays) VALUES ('Kiribati');
INSERT INTO Pays (libelle_pays) VALUES ('Kuwait');
INSERT INTO Pays (libelle_pays) VALUES ('Kyrgyzstan');
INSERT INTO Pays (libelle_pays) VALUES ('Lao Peoples Democratic Republic');
INSERT INTO Pays (libelle_pays) VALUES ('Latvia');
INSERT INTO Pays (libelle_pays) VALUES ('Lebanon');
INSERT INTO Pays (libelle_pays) VALUES ('Lesotho');
INSERT INTO Pays (libelle_pays) VALUES ('Liberia');
INSERT INTO Pays (libelle_pays) VALUES ('Libya');
INSERT INTO Pays (libelle_pays) VALUES ('Liechtenstein');
INSERT INTO Pays (libelle_pays) VALUES ('Lithuania');
INSERT INTO Pays (libelle_pays) VALUES ('Luxembourg');
INSERT INTO Pays (libelle_pays) VALUES ('Macao');
INSERT INTO Pays (libelle_pays) VALUES ('Madagascar');
INSERT INTO Pays (libelle_pays) VALUES ('Malawi');
INSERT INTO Pays (libelle_pays) VALUES ('Malaysia');
INSERT INTO Pays (libelle_pays) VALUES ('Maldives');
INSERT INTO Pays (libelle_pays) VALUES ('Mali');
INSERT INTO Pays (libelle_pays) VALUES ('Malta');
INSERT INTO Pays (libelle_pays) VALUES ('Marshall Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Martinique');
INSERT INTO Pays (libelle_pays) VALUES ('Mauritania');
INSERT INTO Pays (libelle_pays) VALUES ('Mauritius');
INSERT INTO Pays (libelle_pays) VALUES ('Mayotte');
INSERT INTO Pays (libelle_pays) VALUES ('Mexico');
INSERT INTO Pays (libelle_pays) VALUES ('Monaco');
INSERT INTO Pays (libelle_pays) VALUES ('Mongolia');
INSERT INTO Pays (libelle_pays) VALUES ('Montenegro');
INSERT INTO Pays (libelle_pays) VALUES ('Montserrat');
INSERT INTO Pays (libelle_pays) VALUES ('Morocco');
INSERT INTO Pays (libelle_pays) VALUES ('Mozambique');
INSERT INTO Pays (libelle_pays) VALUES ('Myanmar');
INSERT INTO Pays (libelle_pays) VALUES ('Namibia');
INSERT INTO Pays (libelle_pays) VALUES ('Nauru');
INSERT INTO Pays (libelle_pays) VALUES ('Nepal');
INSERT INTO Pays (libelle_pays) VALUES ('Netherlands');
INSERT INTO Pays (libelle_pays) VALUES ('New Caledonia');
INSERT INTO Pays (libelle_pays) VALUES ('New Zealand');
INSERT INTO Pays (libelle_pays) VALUES ('Nicaragua');
INSERT INTO Pays (libelle_pays) VALUES ('Niger');
INSERT INTO Pays (libelle_pays) VALUES ('Nigeria');
INSERT INTO Pays (libelle_pays) VALUES ('Niue');
INSERT INTO Pays (libelle_pays) VALUES ('Norfolk Island');
INSERT INTO Pays (libelle_pays) VALUES ('Northern Mariana Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Norway');
INSERT INTO Pays (libelle_pays) VALUES ('Oman');
INSERT INTO Pays (libelle_pays) VALUES ('Pakistan');
INSERT INTO Pays (libelle_pays) VALUES ('Palau');
INSERT INTO Pays (libelle_pays) VALUES ('Panama');
INSERT INTO Pays (libelle_pays) VALUES ('Papua New Guinea');
INSERT INTO Pays (libelle_pays) VALUES ('Paraguay');
INSERT INTO Pays (libelle_pays) VALUES ('Peru');
INSERT INTO Pays (libelle_pays) VALUES ('Philippines');
INSERT INTO Pays (libelle_pays) VALUES ('Pitcairn');
INSERT INTO Pays (libelle_pays) VALUES ('Poland');
INSERT INTO Pays (libelle_pays) VALUES ('Portugal');
INSERT INTO Pays (libelle_pays) VALUES ('Puerto Rico');
INSERT INTO Pays (libelle_pays) VALUES ('Qatar');
INSERT INTO Pays (libelle_pays) VALUES ('Romania');
INSERT INTO Pays (libelle_pays) VALUES ('Russian Federation');
INSERT INTO Pays (libelle_pays) VALUES ('Rwanda');
INSERT INTO Pays (libelle_pays) VALUES ('Saint Kitts and Nevis');
INSERT INTO Pays (libelle_pays) VALUES ('Saint Lucia');
INSERT INTO Pays (libelle_pays) VALUES ('Saint Martin (French part)');
INSERT INTO Pays (libelle_pays) VALUES ('Saint Pierre and Miquelon');
INSERT INTO Pays (libelle_pays) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO Pays (libelle_pays) VALUES ('Samoa');
INSERT INTO Pays (libelle_pays) VALUES ('San Marino');
INSERT INTO Pays (libelle_pays) VALUES ('Sao Tome and Principe');
INSERT INTO Pays (libelle_pays) VALUES ('Saudi Arabia');
INSERT INTO Pays (libelle_pays) VALUES ('Senegal');
INSERT INTO Pays (libelle_pays) VALUES ('Serbia');
INSERT INTO Pays (libelle_pays) VALUES ('Seychelles');
INSERT INTO Pays (libelle_pays) VALUES ('Sierra Leone');
INSERT INTO Pays (libelle_pays) VALUES ('Singapore');
INSERT INTO Pays (libelle_pays) VALUES ('Sint Maarten (Dutch part)');
INSERT INTO Pays (libelle_pays) VALUES ('Slovakia');
INSERT INTO Pays (libelle_pays) VALUES ('Slovenia');
INSERT INTO Pays (libelle_pays) VALUES ('Solomon Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Somalia');
INSERT INTO Pays (libelle_pays) VALUES ('South Africa');
INSERT INTO Pays (libelle_pays) VALUES ('South Georgia and the South Sandwich Islands');
INSERT INTO Pays (libelle_pays) VALUES ('South Sudan');
INSERT INTO Pays (libelle_pays) VALUES ('Spain');
INSERT INTO Pays (libelle_pays) VALUES ('Sri Lanka');
INSERT INTO Pays (libelle_pays) VALUES ('State of Palestine');
INSERT INTO Pays (libelle_pays) VALUES ('Sudan');
INSERT INTO Pays (libelle_pays) VALUES ('Suriname');
INSERT INTO Pays (libelle_pays) VALUES ('Svalbard and Jan Mayen');
INSERT INTO Pays (libelle_pays) VALUES ('Swaziland');
INSERT INTO Pays (libelle_pays) VALUES ('Sweden');
INSERT INTO Pays (libelle_pays) VALUES ('Switzerland');
INSERT INTO Pays (libelle_pays) VALUES ('Syrian Arab Republic');
INSERT INTO Pays (libelle_pays) VALUES ('Tajikistan');
INSERT INTO Pays (libelle_pays) VALUES ('Thailand');
INSERT INTO Pays (libelle_pays) VALUES ('Timor-Leste');
INSERT INTO Pays (libelle_pays) VALUES ('Togo');
INSERT INTO Pays (libelle_pays) VALUES ('Tokelau');
INSERT INTO Pays (libelle_pays) VALUES ('Tonga');
INSERT INTO Pays (libelle_pays) VALUES ('Trinidad and Tobago');
INSERT INTO Pays (libelle_pays) VALUES ('Tunisia');
INSERT INTO Pays (libelle_pays) VALUES ('Turkey');
INSERT INTO Pays (libelle_pays) VALUES ('Turkmenistan');
INSERT INTO Pays (libelle_pays) VALUES ('Turks and Caicos Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Tuvalu');
INSERT INTO Pays (libelle_pays) VALUES ('Uganda');
INSERT INTO Pays (libelle_pays) VALUES ('Ukraine');
INSERT INTO Pays (libelle_pays) VALUES ('United Arab Emirates');
INSERT INTO Pays (libelle_pays) VALUES ('United Kingdom');
INSERT INTO Pays (libelle_pays) VALUES ('United States');
INSERT INTO Pays (libelle_pays) VALUES ('United States Minor Outlying Islands');
INSERT INTO Pays (libelle_pays) VALUES ('Uruguay');
INSERT INTO Pays (libelle_pays) VALUES ('Uzbekistan');
INSERT INTO Pays (libelle_pays) VALUES ('Vanuatu');
INSERT INTO Pays (libelle_pays) VALUES ('Viet Nam');
INSERT INTO Pays (libelle_pays) VALUES ('Wallis and Futuna');
INSERT INTO Pays (libelle_pays) VALUES ('Yemen');
INSERT INTO Pays (libelle_pays) VALUES ('Zambia');
INSERT INTO Pays (libelle_pays) VALUES ('Zimbabwe');